apiVersion: v1
kind: Secret
metadata:
  name: devops-secrets
type: Opaque
stringData:
  # In real world, use Vault or SealedSecrets. These are base64 defaults for the specific values.
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "dev_secret_password_123!"
  DB_PASSWORD_AUTH: "auth_pass_123"
  DB_PASSWORD_TICKET: "ticket_pass_123"
  JWT_SECRET: "super_secret_jwt_key_dev"
  REFRESH_SECRET: "super_secret_refresh_key_dev"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-config
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME_AUTH: "auth_db"
  DB_NAME_TICKET: "ticket_db"
  DB_NAME_AUDIT: "audit_log_db"
